# Replace source folder "docusign" with target source folder

version: '3'
services:

  # DATABASE 
  db:
    container_name: mysqldb 
    image: mysql:5.7
    volumes:
      - ./docker-resource/database/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./docker-resource/database/mysql/logs:/var/log/mysql
      - ./docker-resource/database/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "3306:3306"

  # PHPMYADMIN   
  phpmyadmin:
    container_name: phpmyadmin_service
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    depends_on:
      - db    

  # APPLICATION  
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker-resource/apache-php/Dockerfile
      args:
        uid: ${UID}
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - "DB_PORT=3306"
      - "DB_HOST=db"
    ports:
      - "80:80"
    volumes:
      - ../docusign/:/var/www/html
      - ./docker-resource/apache-php/logs/error.log:/var/log/apache2/error.log
      - ./docker-resource/apache-php/php/updates.ini:/usr/local/etc/php/conf.d/updates.ini
    depends_on:
      - db
    links:
      - db:mysqldb
