# Replace source folder "docusign" with target source folder

version: "3.2"
services:

  # Database Service    
  mysql:
    container_name: docusign_db
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - ./database/mysql/config/my.cnf:/etc/mysql/my.cnf      
      - ./database/mysql/logs:/var/log/mysql
      - ./database/mysql/data:/var/lib/mysql  
    environment:     
      - "MYSQL_ROOT_PASSWORD=docusigndb" 
    ports: 
      - "3306:3306"  

  # PHP Service  
  php:
    container_name: docusign_php7
    build: './docker-resource/php/'
    working_dir: /var/www/html    
    volumes:
      - ../docusign/:/var/www/html
    networks:
      - backend
  
  # Web Server Service    
  apache:
    container_name: docusign_apache
    build: './docker-resource/apache/'
    depends_on:
      - php
      - mysql  
    ports:
      - "8080:80"
    volumes:
      - ../docusign/:/var/www/html/
    networks:
      - frontend
      - backend  

  
networks:
  frontend:
  backend: