# Replace source folder "docusign" with target source folder

version: '3'
services:

  # DATABASE 
  db:    
    image: mysql:5.7   
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "3306:3306"

  # PHPMYADMIN   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    depends_on:
      - db    

  # APPLICATION  
  app:
    build:
      context: .
      dockerfile: ./docker-resource/apache-php/Dockerfile
      args:
        uid: ${UID}
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - "80:80"
    volumes:
      - ../laravel/:/var/www/html
    depends_on:
      - db
